### PR TITLE
Add printf to __THCudaCheck fail clause, in case stack unwind itself …

### PR DESCRIPTION
**Pull request by hughperkins**
…crashes

Address https://github.com/torch/cutorch/issues/329

### CODE REVIEW

**Comment by hughperkins** [comment]
Hmmm, although note that this will print a ton of FAILs during unwind.  Maybe I should add a `static` var, and only print hte first failure perhaps?

**Comment by hughperkins** [comment]
Modified to only print the first failure, and then assume we're already unwinding, since THError will already have been called at least once.

**Comment by soumith** [comment]
are you sure this actually helps in improving errors? (I dont think so). See my comment on CUDA_LAUNCH_BLOCKING on the other thread.

**Comment by hughperkins** [comment]
It was a prerequisite for diagnosing https://github.com/torch/cutorch/pull/332 (which took me almost my entire day by the way... of which 3-4 hours was working my way backwards far enough to make the change in this PR; I spent several hours instrumenting Storage, trying to work out why my storage was broken; checking pairs of allocaitons and free.  All a complete waste of time of course, since the root cause was prior to the 8,000 frees...)

**Comment by soumith** [comment]
that sounds horrible, i feel sorry for you :)
If you can give me a stack trace output of with this, and without this -- that'll help me understand how this printf is helpful.

**Comment by hughperkins** [comment]
Original stack trace was simply something like:

```
segmentation error
```
That was it :-P  That was the entire output.

If you opened gdb on this line, with a breakpoint, it just unhelpfully showed a call from lua into storage_free.

After instrumenting Storage a bit, I got the following output:

https://gist.github.com/hughperkins/ce225700d0df80b908a7

After instrumenting CudaCheck, I got:

https://gist.github.com/hughperkins/2332cc8f8227454b3960

... which makes the location of hte problem significantly more obvious.  It's nothing to do with Storage_free in fact ....

**Comment by hughperkins** [comment]
(note: the seg faults occurs right at the end of the logfile, in both cases.  the seg fault terminates the program, and closes the logfile; therefore it's reasonable to suppose that the lsat copule of lines of the log are the cause of the segfault.  Which is kind of true. But misleading)

**Comment by soumith** [comment]
ok thanks for the tracing. I expected the line below, i.e.
_THError(file, line, "cuda runtime error (%d) : %s", err,
               cudaGetErrorString(err));

should do the same thing as your printf, but clearly it does not print file/line number on segfault, weird.

**Comment by hughperkins** [comment]
Yeah, it only prints stuff *after* unwind.  And if unwind crashes... :-(

**Comment by hughperkins** [comment]
(Although plausibly one could modify _THError to do a printf before commencing unwind I suppose?)

**Comment by soumith** [comment]
ok this seems reasonable to merge. but I'd want the cudaGetErrorString to also be present in the printf, can you modify that.

**Comment by hughperkins** [comment]
> ok this seems reasonable to merge. but I'd want the cudaGetErrorString to also be present in the printf, can you modify that.

Ok, sounds good.  I'll update that.

By the way for _THError.... curiously it seems that it *should* do a printf in fact.  Here is _THError, in torch7's general.c:

```
void _THError(const char *file, const int line, const char *fmt, ...)
{
  char msg[2048];
  va_list args;

  /* vasprintf not standard */
  /* vsnprintf: how to handle if does not exists? */
  va_start(args, fmt);
  int n = vsnprintf(msg, 2048, fmt, args);
  va_end(args);

  if(n < 2048) {
    snprintf(msg + n, 2048 - n, " at %s:%d", file, line);
  }

  (*torchErrorHandlerFunction)(msg, torchErrorHandlerData);
}
```
What is torchErrorHandlerFunction?  It's:
```
static __thread void (*torchErrorHandlerFunction)(const char *msg, void *data) = defaultTorchErrorHandlerFunction;
```
And defaultTorchErrorHandlerFunction is:
```
static void defaultTorchErrorHandlerFunction(const char *msg, void *data)
{
  printf("$ Error: %s\n", msg);
  exit(-1);
}
```
Seems like it should printf in fact???

**Comment by hughperkins** [comment]
Is it possible that cudaGetErrorString fails???

**Comment by soumith** [comment]
that's a scary thought, but maybe :)

**Comment by hughperkins** [comment]
It's annoyingly hard to test unfortunately.   I tried creating a test case like:
```
require 'cutorch'

a = torch.CudaTensor(128, 128):fill(-1)
b = torch.CudaTensor(128, 128):fill(-1)
c = torch.CudaTensor(128, 128)
local d = {}
for i=1,10000 do
  d[i] = c:narrow(2,1,50)
end
c:scatter(1, b, c)
c:max()
```
... but doesnt reproduce the seg fault.  The only way I have to reproduce the issue is to run my training program, which is quite slow.

Anywya, I guess I should dig a bit, figure out why THError isnt doing printf and/or if cudaGetErrorString is failing.

**Comment by hughperkins** [comment]
Well, one observation is that one of the first htings that happens when I run the program is that `THSetErrorHandler` is called, so the error handler may not be the one we think it is?

**Comment by hughperkins** [comment]
Ah-hah!  In torch7, utils.c:

```
static void luaTorchErrorHandlerFunction(const char *msg, void *data)
{
  lua_State *L = data;
  luaL_error(L, msg);
}

static int torch_updateerrorhandlers(lua_State *L)
{
  THSetErrorHandler(luaTorchErrorHandlerFunction, L);
  THSetArgErrorHandler(luaTorchArgErrorHandlerFunction, L);
  return 0;
}
```

And `luaTorchErrorHandlerFunction` is a printf-free zone.

**Comment by hughperkins** [comment]
Sooo... we could modify `luaTorchErrorHandlerFunction` in `utils.c` to have a `printf` first, but I suspect that things in a non-cuda world are maybe more well-behaved?  So maybe we just fix it in `THCudaCheck` for now, since maybe the issue doesnt occur in torch7 world?

**Comment by hughperkins** [comment]
Ok:
- added `cudaGetErrorString`
- also made it print to `stderr`

Example output:
```
THCudaCheck FAIL file=/home/ubuntu/git/cutorch/lib/THC/THCTensorMath.cu line=303 error=77 : an illegal memory access was encountered
luajit: cuda runtime error (77) : an illegal memory access was encountered at /home/ubuntu/git/cutorch/lib/THC/generic/THCStorage.c:147
```

**Comment by soumith** [comment]
Thank you so much!

**Pull request merged**
