### PR TITLE
temporarily force pseudo-fp16 mode (HAS_HALF_INSTRUCTIONS=FALSE) for …

### PR DESCRIPTION
**Pull request by borisfom**
…Pascal: as per my suggestion in https://github.com/torch/cutorch/issues/520

### CODE REVIEW

**Comment by borisfom** [comment]
@soumith: FYI, next NVIDIA Torch package will be shipping with this change.

**Comment by soumith** [comment]
we really prefer that you guys do not fork torch. i am not sure why you are going that route.

**Comment by soumith** [comment]
and for a proper fix so that P100 users aren't left in the dust, please see discussion here: https://github.com/torch/cutorch/issues/544

**Comment by borisfom** [comment]
@soumith: we needed this PR for the release, and it was not integrated so we had to use the fork.

**Pull request closed without merging**
