### PR TITLE
Fix RNG issues.

### PR DESCRIPTION
**Pull request by dominikgrewe**
Reset MTGP32 constants when setting the seed.
Always generate multiples of 256 numbers (discarding the ones not
needed).

### CODE REVIEW

**Comment by dominikgrewe** [comment]
Fixes problem as described in torch/torch7#167

**Comment by jucor** [comment]
Great fix Dominik, thanks! For the record: the only actual downside is very minor and not worth worrying about. In the worst case the period of the generator is divided by 256, but since MGTP32 has period  2^11213-1, dividing it by 256 makes it way long enough.

**Comment by dominikgrewe** [comment]
To give some context to Julien's comment:
This fix also solves the issue discussed in #97 . I've tested the RNG using the dieharder test suite on all tests that accept floats as inputs. Whereas before all tests started failing when only generating 10s or 100s of numbers, they now succeed even when only generating single numbers at a time.

**Comment by soumith** [comment]
that is great. thanks @dominikgrewe

**Pull request merged**
