### PR TITLE
Move more functions into generic

### PR DESCRIPTION
**Pull request by killeent**
This PR moves the following Tensor functions into the generic directory:

- mean/meanall are extended to all tensor types
- clamp to all tensor types
- cross to all tensor types
- cmin/cmax to all tensor types
- addcmul/addcdiv to all tensor types
- std/stdall to float/half/double tensors
- var/varall to float/half/double tensors
- norm/normall to float/half/double tensors
- renorm to float/half/double tensors
- lerp to float/half/double tensors
- Required refactoring a lot of float specific code into .cuh files.

Test Plan:

updated unit tests to compare using new tensor types

### CODE REVIEW

**Comment by borisfom** [comment]
@killeent: can we coordinate that with https://github.com/torch/cutorch/issues/515 ?

**Comment by borisfom** [comment]
Also, THCNumeric.h is getting way too much of code duplication. Let me submit a PR for refactored version that would be a small fraction of current size and allow for less changes going forward.

**Comment by soumith** [comment]
i will be merging this, as it's a big functional PR, and it brings a lot of features in. Delaying this will really result in merge conflicts and really hard refactoring work.

working with #515 should follow.

**Comment by borisfom** [comment]
@soumith: sure, merging this fast what I was hoping for! There is nothing contradictory between this and pseudo-float work, except that we touch the same files and moving stuff around.

**Pull request merged**
