### PR TITLE
Bugfix for multinomial distribution

### PR DESCRIPTION
**Pull request by pavanky**
- Ensures the index of the first bin from the cdf is returned.

- potential fix for #636

### CODE REVIEW

**Comment by pavanky** [comment]
I am not 100% sure this is the right fix, but the tests passed for multiple runs.

**Comment by soumith** [comment]
cc: @wickedfoo

**Comment by pavanky** [comment]
The test mentioned in #636  still fails after running a few more times. However, the frequency at which it fails seems to have decreased.

**Comment by wickedfoo** [comment]
Seems legit and makes sense to me, why not :)

**Pull request merged**
