### PR TITLE
Add CudaHostAllocator

### PR DESCRIPTION
**Pull request by dominikgrewe**
* A new Torch allocator that uses cudaMallocHost.
* cutorch.createCudaHostTensor(...) to create FloatTensor allocated with
  CudaHostAllocator.

### CODE REVIEW

**Comment by soumith** [comment]
nice. pinned memory from lua-land is a reality now. cc: @tudor

**Comment by szagoruyko** [comment]
this PR has broken all the rocks that use cutorch
```
[100%] Building NVCC (Device) object CMakeFiles/cunn.dir/cunn_generated_init.cu.o
In file included from /tmp/luarocks_cunn-scm-1-6084/cunn/init.cu:2:
/usr/local/include/THC/THC.h:5:10: fatal error: 'THCAllocator.h' file not found
#include "THCAllocator.h"
         ^
1 error generated.
```

**Comment by soumith** [comment]
oh oh, I guess dominik forgot to include it in CMakeLists.txt
I guess we need contbuild for cutorch OSS asap.

**Comment by dominikgrewe** [comment]
Sorry about that!! I'll prepare a patch.

**Comment by soumith** [comment]
I just fixed it in trunk via https://github.com/torch/cutorch/commit/26b3f2164ea942cd7db7e38304ee9d2c83cd9fd9

verifying.

**Comment by dominikgrewe** [comment]
Thanks Soumith! I think the .c file is twice in CMakeLists.txt now. Only the header was missing.

**Comment by soumith** [comment]
Ok I verified that trunk is unbroken.

**Comment by soumith** [comment]
removed the duplicate. thanks.

**Pull request merged**
