### PR TITLE
Extend README with new tensor types

### PR DESCRIPTION
**Pull request by bshillingford**
The README was a bit out of date. Added a listing of new tensor types including FP16, and `createCudaHostTensor`.

### CODE REVIEW

**Comment by fmassa** [comment]
I think we should also add a notice saying that at the moment the only supported operations on these tensors are copy. What do you think ?

**Comment by bshillingford** [comment]
Agreed, I've added that as a note to the intro and the section.

**Comment by soumith** [comment]
Awesome! Thanks Brendan.

**Comment by bshillingford** [comment]
Thanks!

**Pull request merged**
