### PR TITLE
EXPERIMENTAL improve dependencies during build

### PR DESCRIPTION
**Pull request by hughperkins**
This is mostly for discussion purposes for now.  In theory, what it does is:
- if you build twice, without making any changes, the second time, bulid almost instant
- if you then `touch` one .cu file, and rebuild, that .cu file, and only that .cu file, will be rebuilt
- no more messages about 'dependency not found, removing'

Quite experimental for now, not very tested.  I don't reckon we should merge to master for now, but maybe worth trying for a bit, see how it goes?

Relates to following issues:
- [Annoying non-existent dependency file warnings](https://github.com/torch/cutorch/issues/100)
- [Rerunning make causes whole cutorch to rebuild again](https://github.com/torch/cutorch/issues/171)

### CODE REVIEW

**Comment by Atcold** [comment]
> no more messages about 'dependency not found, removing'

Sweet!

**Comment by hughperkins** [comment]
Thanks!   I reckon it'd be good for a few people to try it first though, and check does/doesnt work.  Actually, I think I might split into two commits, so it's clearer what it does, which will be:
- commit 1: copy FindCUDA files into cutorch, renaming them to FindCUDA_streamlined, to avoid naming conflicts
- commit 2: modification to how dependency handling works

**Comment by hughperkins** [comment]
How this is intended to work:

Background:
- dependency handling is handled by the `add_custom_command` at https://github.com/hughperkins/cutorch/blob/a9dc0709c900295ba2731d18083d7800e815d880/cmake/FindCUDA_streamlined.cmake#L1294-L1296
  - it has a looott of dependencies, including .cu files (good), .h files (good), the cunn.dir directory (less good), the generated build script itself (less good)
- it's handled all over again during build by the lines at https://github.com/hughperkins/cutorch/blob/a9dc0709c900295ba2731d18083d7800e815d880/cmake/FindCUDA_streamlined/run_nvcc.cmake#L181-L234
  - these are superfluous I think, since we're always running cmake, via luarocks
  - these lines rerun `nvcc -M`, to get dependencies list
  - these lines are the ones created the `dependency removed` messages

So, in this change:
- remove some of the dependencies from the `add_custom_command` command, eg the dependnecy on the build script, and on `cunn.dir`
- remove the superfluous additional checking from `run_nvcc.cmake`

**Comment by hughperkins** [comment]
(hmmm, but the new, unsquashed, version doesnt seem to fix the dependencies :-P  checking...)

**Comment by hughperkins** [comment]
Hmmm, seems not to work now :-O  Maybe I still had some hacks in my global directories, and after reinstalling `cmake-data`, the contents of CUDA_NVCC_DEPEND at line 1298 seem radically different :-O

**Comment by hughperkins** [comment]
(Closing this for now, since doesnt work at moment :-P )

**Comment by hughperkins** [comment]
Hmmm, cant reopen after force pushing :-(

**Pull request closed without merging**
