### PR TITLE
Add copyAsync for asynchronous copies between host and device.

### PR DESCRIPTION
**Pull request by dominikgrewe**
As discussed in #216.

Only works for contiguous Float- and CudaTensors.

### CODE REVIEW

**Comment by dominikgrewe** [comment]
@soumith @wickedfoo Any thoughts on this?

**Comment by wickedfoo** [comment]
Looks fine to me, only comment is that this won't really do much (the copy is still effectively synchronous; it copies to a small pinned staging buffer managed by the driver which is then async copied to the GPU; if the buffer is too large, it loops until the last chunk is copied over) until we have a story for CPU pinned memory allocations, and some way to prevent the GC cleanup of that memory while any copies are completing.

I think the story in the longer term to prevent GC issues would be to addref the storage while performing an async copy, then use `cudaStreamAddCallback` in the current stream for the device for which we're copying memory to/from that will add the storage to an allowed cleanup list, which we look at the next time we try to malloc or free CUDA memory, at which point we release the reference, potentially freeing the storage. The reason why we can't release the memory in the callback is because CUDA APIs apparently can't be called in the callback. I don't know in what CPU thread the callback is made either yet.

**Comment by dominikgrewe** [comment]
We do have `cutorch.createCudaHostTensor` which allocates pinned memory.

You're right about the GC problem, but isn't that the case with regular CudaTensors and async operations already?

**Comment by wickedfoo** [comment]
For regular CudaTensors it isn't an issue, because cudaFree is synchronizing and will wait for the completion of all operations on that memory (across all streams). I don't know if it is globally synchronizing (across all devices) or just the current device that holds the memory that is being reclaimed.

I guess the question is if freeing pinned CPU memory is synchronizing. If not, then this isn't a problem; if it is, then we need some kind of dependency wait.

**Comment by wickedfoo** [comment]
(sorry edited the above comment; if it is synchronizing then it isn't an issue; if it isn't then we have to do something)

**Comment by dominikgrewe** [comment]
Yes, I forgot about that. Not sure if cudaFreeHost also implicitly synchronizes. I'll try to find out.

**Comment by dominikgrewe** [comment]
Thanks @wickedfoo. I've updated the patch.

**Comment by wickedfoo** [comment]
looks good to me!

**Comment by wickedfoo** [comment]
I guess we should figure out the story with pinned memory frees though.

**Comment by soumith** [comment]
thanks @dominikgrewe

**Comment by dominikgrewe** [comment]
Just to update: My contact at NVIDIA told me that `cudaFreeHost` waits for operations on _all_ devices before the memory is freed. So everything is safe.

`cudaFree` waits for operations on the device that the memory was allocated on to finish.

**Comment by wickedfoo** [comment]
Ah, cool.

**Pull request merged**
