### PR TITLE
stop cutorch clobbering cltorch, if `require`d after cltorch

### PR DESCRIPTION
**Pull request by hughperkins**
This isnt strictly necessary any more, since cltorch now runs from a stable torch distro.  But it might still be nice to add this sometime?

This patch makes the cutorch monkey-patch not overwrite any other module's existing monkey-patching on getmetatable(RealTensor).copy, in the case that `cutorch is`require`d after the other module.

### CODE REVIEW

**Comment by hughperkins** [comment]
(Relevant doc https://github.com/hughperkins/cltorch#co-existence-with-cutorch )

**Comment by soumith** [comment]
@torchbot test this

**Comment by soumith** [comment]
@torchbot test this

**Comment by soumith** [comment]
@torchbot test this

**Pull request closed without merging**
