### PR TITLE
Get rid of warp-synchronous code

### PR DESCRIPTION
**Pull request by ngimel**
Time to get rid of warp-synchronous code - it is unsafe.

### CODE REVIEW

**Comment by wickedfoo** [comment]
looks good to me

are there finer-grained synchronization primitives coming (warp-wide barriers)?

**Comment by ngimel** [comment]
Yes, but no details yet.

**Comment by soumith** [comment]
thanks!

**Comment by killeent** [comment]
Great. As @wickedfoo has previously mentioned, I had to disable these to get any sort of useful output from the racecheck tool.

**Pull request merged**
