### PR TITLE
Fix gcc 4.4.7 build.

### PR DESCRIPTION
**Pull request by gchanan**

### CODE REVIEW

**Comment by soumith** [comment]
auto also isn't supported afaik

**Comment by soumith** [comment]
at least it was giving me an error

**Comment by gchanan** [comment]
it was giving you an error because emplace doesn't exist, so it doesn't know the type for auto.

**Comment by gchanan** [comment]
e.g. https://github.com/torch/cutorch/commit/eb3fe1904d18934f177972ad89c973be92b97dc2 is the original THCCachingHostAllocator commit has auto.

**Comment by soumith** [comment]
got it. thanks!

**Pull request merged**
